catalogue/urls.py
from django.urls import path
from . import views

app_name = 'catalogue'

urlpatterns = [
    path('', views.main, name="main"),
    path('category/add/', views.CreateCategory.as_view(), name='add_category'),
    path('delete/category/<int:pk>/', views.delete_category, name="delete_category"),
    path('item/add/', views.ItemCreateView.as_view(), name='add_item'),
    path('variant/add/', views.CreateVariant.as_view(), name='add_variant'),
    path('update-variant/<int:pk>/', views.UpdateVariant.as_view(), name='update_variant'),
    path('update-item/<int:pk>/', views.UpdateItem.as_view(), name='update_item'),
    path('update-category/<int:pk>/', views.UpdateCategory.as_view(), name='update_category'),
]

kits/urls.py
from django.urls import path
from . import views

app_name = 'kit'

urlpatterns = [
    path('', views.student_index, name='student_index'),
    path('add-item/', views.CreateItemView.as_view(), name='item_form'),
    path('create-kit/', views.kititem_view, name='create_kititems'),
    path('kititem-form/', views.get_kititem_form, name='kititem_form'),
    path('allocation/list/', views.allocation_list, name="allocate_list"),
    path('allocate-sale/', views.allocate_sale, name="allocate_sale"),
    path('allocate-save/<int:pk>/', views.KitAllocationDetailView.as_view(), name="allocate_save_detail"),
    path('alloccate/update/<int:pk>/', views.UpdateKitAllocation.as_view(), name="update_allocation"),
    path('update/kit/<int:kit_id>/', views.update_kit, name="update_kit"),
    path('delete/kititem/<int:pk>/', views.delete_kititem, name="delete_kititem"),
    path('delete/kit/<int:pk>/', views.delete_kit, name="delete_kit"),
]

stock_management/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', TemplateView.as_view(template_name='index.html'), name='index'),
    path('catalogue/', include('catalogue.urls', namespace='catalogue')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('stock/', include('stock.urls', namespace='stock')),
    path('kit/', include('kits.urls', namespace='kit')),
    path('auth/', include('authapp.urls', namespace='authapp')),
    path('allocate/', include('allocate.urls', namespace='allocate')),
    path('employees/', include('employees.urls', namespace='employees')),



] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

kits/models.py
from django.db import models
from stock.models import Variant
from authapp.models import Student
from datetime import datetime

# Create your models here.
class Kits(models.Model):
    FR = 'free'
    PD ='paid'
    
    KIT_TYPE = [
        (FR, 'Free'),
        (PD, 'Paid'),
    ]
    name = models.CharField(max_length=50)
    type = models.CharField(max_length=50, choices=KIT_TYPE, default=FR)
    description = models.CharField(max_length=254, blank=True)
    academic_year = models.CharField(max_length=50)
    
    class Meta:
        verbose_name = 'Kit'
        verbose_name_plural = 'Kits'
    
    def __str__(self):
        return f'{self.name} - {self.type}'
    
    def item_count(self):
       package = KitItems.objects.filter(kit=self).count()
       return package
   
    def total_price(self):
        total = 0
        for item in KitItems.objects.filter(kit=self):
            total += item.price * item.quantity
        return total
   
class KitItems(models.Model):
    kit = models.ForeignKey(Kits, on_delete=models.CASCADE)
    variant = models.ForeignKey(Variant, on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField(default=1)
    price = models.PositiveIntegerField(default=0)
    
    class Meta:
        verbose_name = 'Kit Item'
        verbose_name_plural = 'Kit Items'
        
    def __str__(self):
        return f'{self.variant}'
        
        
class KitAllocation(models.Model): 
    student = models.ForeignKey(Student, on_delete=models.CASCADE)
    kit = models.ForeignKey('Kits', on_delete=models.CASCADE)
    kititems = models.ManyToManyField(KitItems)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    
    class Meta:
        verbose_name = 'Kit Allocation'
        verbose_name_plural = 'Kit Allocations'
        
    def __str__(self):
        return f'{self.student}_{self.student.enrollement}'
    
    def total_payment(self):
        total = 0
        for item in self.kititems.all():
            total += item.price * item.quantity
        return total

kits/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.generic.edit import CreateView, DeleteView, UpdateView
from .models import *
from .forms import *
from django.urls import reverse_lazy
from django.forms import formset_factory
from django.contrib import messages
from django.views.generic import TemplateView, DetailView
from django.db import transaction
from .utils import find_allocation
from stock.models import StockTransactions, Stock
from django.contrib.contenttypes.models import ContentType
from stock.utils import update_stock_quantity
from django.db.models import Sum, F
from django.forms import formset_factory, modelformset_factory
from django.utils import timezone
from django.contrib.auth.decorators import login_required
from authapp.decorators import is_manager

@login_required
@is_manager
def student_index(request):
    return redirect('kit:item_form')

def create_kit(request):
    return render(request, 'kits/item_form.html')
    

class CreateItemView(CreateView):
    model = Kits
    form_class = KitForm
    template_name = 'kits/item_form.html'
    success_url = reverse_lazy('kit:create_kititems')
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        kits = Kits.objects.all()
        context['kits'] = kits
        return context
    
    def form_valid(self, form):
        form.save()
        messages.success(self.request, 'Item added successfully')
        return super().form_valid(form)
    
    
def kititem_view(request):
    if request.method == 'POST':
        form_count = request.POST.get('form_count')
        KitItemFormSet = formset_factory(KitItemsForm, extra=int(form_count), max_num=int(form_count))
        
        post_data = request.POST.copy()
        first_kit_id = post_data.get('form-0-kit')
        
        for i in range(1, int(form_count)):
            post_data[f'form-{i}-kit'] = first_kit_id
        
        formset = KitItemFormSet(post_data)
        
        if formset.is_valid():
            for form in formset:
                form.save()
            
            messages.success(request, 'Kit items added successfully')
            return render(request, 'kits/kit_form.html')
        else:
            print('errrors',formset.errors)
            messages.error(request, 'Error in form')
            return render(request, 'kits/kit_form.html', {'formset': formset})
        
    kit_packs = KitItems.objects.values('kit__type', 'kit__academic_year', 'kit__name').annotate(kit_total=Sum('quantity'), payable_amount=Sum('price'))
    context = {'kit_packs': kit_packs} 
    
    return render(request, 'kits/kit_form.html', context)



def update_kit(request, kit_id):
    context = dict()
    """
    View for updating a kit item.
    """
    kit = Kits.objects.get(pk=kit_id)

    if request.method == 'POST':
        post_data = request.POST.copy()
        kit_form = ItemAndKitForm(post_data, instance=kit)
        kititems_formset = BaseKitFormSet(request.POST, instance=kit)
        
      
        if kititems_formset.is_valid():
            kit_form.save()
            kititems_formset.save()
            messages.success(request, 'Kit updated successfully')
            return redirect('kit:item_form')
        else:
            print('formset',kititems_formset)
            print('form',kit_form.errors)
            messages.error(request, 'Something went wrong. Try again.')
            
        return redirect('kit:update_kit', kit_id=kit_id)
    
    kit_form = ItemAndKitForm(instance=kit)
    kititems_formset = BaseKitFormSet(instance=kit)

    
    for form in kititems_formset:
        form.fields['price'].widget.attrs.update({
            'readonly':True if kit.type == Kits.FR else False,
        })

        form.fields['price'].widget.attrs.update({
            'class': 'form-control'
        })
        
        for field in form.fields.values():
            field.label = ''
    
    
    context['kit_form'] = kit_form
    context['kititems_formset'] = kititems_formset
    
    return render(request, 'kits/update_kit.html', context)



def delete_kititem(request, pk):
    kit_id = request.GET.get('kit')
    print('kit id',kit_id)
   
    kititem = get_object_or_404(KitItems, pk=pk)
    kititem.delete()
    messages.success(request, 'Kit item deleted successfully')
    return redirect('kit:update_kit', kit_id=int(kit_id))

def get_kititem_form(request):
    form_count = request.POST.get('form_count', 1)
    KitItemFormSet = formset_factory(KitItemsForm, extra=int(form_count), max_num=int(form_count))
    formset = KitItemFormSet()
 
    context = {'formset': formset, 'form_count': form_count}
    return render(request, 'kits/partials/kititem_form_part.html', context)


def delete_kit(request, pk):
    kit = get_object_or_404(Kits, pk=pk)
    kit.delete()
    messages.success(request, 'Kit deleted successfully')
    return redirect('kit:item_form')


def allocation_list(request):
    kit_allocations = KitAllocation.objects.all()
    context = {'kit_allocations': kit_allocations}
    
    
    if request.GET.get('search'):
       kit_allocations = find_allocation(request.GET.get('search'))
       context = {'kit_allocations': kit_allocations}
        
    return render(request, 'kits/allocation_list.html', context)

def allocate_sale(request):
    
    if request.method == 'POST':
        post_data = request.POST.copy()
        
        enrollement = post_data.get('enrollement')
        phone = post_data.get('phone', '')
        kit = Kits.objects.get(pk=post_data.get('kit'))

        with transaction.atomic():
            student, created = Student.objects.get_or_create(
                enrollement=enrollement,
                defaults={
                    'name': post_data.get('name'),
                    'program': post_data.get('program'),
                    'phone':post_data.get('phone'),
                    'admission_year': post_data.get('admission_year'),
                }
            )
            
            
            if kit.type == Kits.FR:
                already_allocated = KitAllocation.objects.filter(
                    student=student,
                    kit__type=Kits.FR,
                    kit__academic_year=kit.academic_year
                ).exists()

                if already_allocated:
                    messages.error(request, 'This student has already been allocated a free kit for this academic year.')
                    return redirect('kit:allocate_sale')

                kit_alloc_obj = KitAllocation.objects.create(student=student, kit=kit)
                kit_alloc_obj.kititems.set(post_data.getlist('kititems'))
                
                for item in kit_alloc_obj.kititems.all():
                    Stock.objects.filter(variant=item.variant).update(
                        quantity=F('quantity') - item.quantity,
                        movement_type = Stock.OT,
                        updated_at = timezone.now()
                    )
                    
                messages.success(request, 'Kit allocated successfully.')
                return redirect('kit:allocate_sale')
            elif kit.type == Kits.PD:
                kit_alloc_obj = KitAllocation.objects.create(student=student, kit=kit)
                kit_alloc_obj.kititems.set(post_data.getlist('kititems'))
                messages.success(request, 'Kit allocated successfully.')
                return redirect('kit:allocate_sale')
               



    if request.headers.get('hx-request'):
        initial = {
            'name': request.GET.get('name'),
            'enrollement': request.GET.get('enrollement'),
            'program': request.GET.get('program'),
            'admission_year': request.GET.get('admission_year'),
        }
        
        type = request.GET.get('type', '0')
        stdform = StudentForm(initial=initial)
        allocform = KitAllocationForm(type=type)
        
        context = {'stdform': stdform, 'allocform': allocform, 'type': type}
        return render(request, 'kits/allocate_sale.html', context)
        
    stdform = StudentForm()
    allocform = KitAllocationForm()
    context = {'stdform': stdform, 'allocform': allocform}
    return render(request, 'kits/allocate_sale.html', context)


class KitAllocationDetailView(DetailView):
    model = KitAllocation
    context_object_name = 'kit_alloc'
    template_name = 'kits/allocate_sale_detail.html'
    
    
class UpdateKitAllocation(UpdateView):
    model = KitAllocation
    form_class = KitAllocationForm
    template_name = 'kits/allocate_sale_update.html'
    type = None
    
    
    def get(self, request, *args, **kwargs):
        self.object = self.get_object()
        self.type = request.GET.get('type') or self.object.kit.type
        return super().get(request, *args, **kwargs)

    def get_form(self, form_class=None):
        form = super().get_form(form_class)
        form.fields['kititems'].queryset = KitItems.objects.filter(kit__type=self.type)
        form.fields['kit'].queryset = Kits.objects.filter(type=self.type)
        return form

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['kit_alloc'] = self.object
        context['allocform'] = self.form_class(instance=self.object, type=self.type)
        context['stdform'] = StudentForm(instance=self.object.student)
        context['type'] = self.type
        return context
    
    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        self.type = request.POST.get('type') or self.object.kit.type
        
        form_data = request.POST.copy()
        
        stdform_data = {
            'name': form_data.get('name'),
            'enrollement': form_data.get('enrollement'),
            'program': form_data.get('program'),
            'admission_year': form_data.get('admission_year'),
        }
        
        allocform_data = {

kits/templates/kits/allocate_sale.html
{% extends "./main.html" %}
{% load static %}




{% block table %}
<button class="btn btn-sm btn-primary" onclick="history.back()">Back</button>
{% if messages %}
    {% for message in messages %}
        <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
            {{ message }}
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
    {% endfor %}
{% endif %}

<div class="row">
    <div class="col-md-8 mx-auto">
        <form action="{% url 'kit:allocate_sale' %}" method="POST" class="rounded p-2" style="border:1px solid #c51315">
            {% csrf_token %}
            <h3 class="text-danger">Allocate Kit</h3>
            {{stdform}}

            <div id="alloc_form">
                <label for="">{{ allocform.type.label }}</label>
                <div class="mt-2" id="id_type">

                        {% for text, val in allocform.fields.type.choices %}
                        <div>
                            <label for="{{ allocform.type.id_for_label}}">
                                <input type="radio" name="{{ allocform.type.html_name }}" value="{{ val }}" required
                                {% if val == type %} checked {% endif %}
                                hx-get="{% url 'kit:allocate_sale' %}"
                                hx-trigger="change"
                                hx-target="#alloc_form"
                                hx-select="#alloc_form"
                                hx-include="#alloc_form"
                                hx-swap="outerHTML">
                                {{ text|capfirst }}
                            </label>
                        </div>
                        {% endfor %}
                    
                </div>

                <div class="form-group">
                    {{ allocform.kit.label }}
                    {{ allocform.kit }}
                </div>

                <div class="form-group">
                    <label for="{{ allocform.kititems.id_for_label}}" class="form-label mb-0">{{ allocform.kititems.label }}</label><br>
             

                    <ul>
                        {% for kititem in allocform.fields.kititems.queryset %}
                            <li class="text-center">
                                <input type="checkbox" 
                                    value="{{ kititem.pk }}" 
                                    name="{{ allocform.kititems.html_name }}" 
                                    id="item_id_{{ forloop.counter }}" {% if not kititem.variant.is_stocked %} disabled {% endif %}>
                                <label for="item_id_{{ forloop.counter }}" class="text-center">
                                    <figure class="figure m-0 fw-bold">
                                        {% if kititem.variant.photo%}
                                        <img src="{{ kititem.variant.photo.url }}" alt="photo_{{forloop.counter}}" class="figure-img img-fluid rounded m-0">
                                        {% else %}
                                        <img src="{% static 'images/dummy.png' %}" alt="No Image" class="figure-img img-fluid rounded m-0">
                                        {% endif %}

                                        {% if kititem.variant.is_stocked %} <p class="text-success fw-normal m-0" style="font-size:.7em">In Stock</p>{% else %} <p class="text-danger  fw-normal m-0" style="font-size:.7em">Out Of Stock</p> {% endif %}
                                        <figcaption class="figure-caption text-center  m-0">{{ kititem.variant.name}}</figcaption>
                                    </figure>
                                </label>
                                
                            </li>
                        {% endfor %}
                    </ul>
                </div>
            </div>
            <button class="btn btn-danger w-100">Submit</button>
        </form>
    </div>
</div>
{% endblock table %}

kits/templates/kits/allocate_sale_update.html
{% extends "./main.html" %}
{% load static %}




{% block table %}
<button class="btn btn-sm btn-primary" onclick="history.back()">Back</button>
{% if messages %}
    {% for message in messages %}
        <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
            {{ message }}
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
    {% endfor %}
{% endif %}

<div class="row">
    <div class="col-md-8 mx-auto">
        <form action="" method="POST" class="rounded p-2" style="border:1px solid #c51315">
            {% csrf_token %}
            <h3>Update Kit (ID:{{ kit_alloc.pk }})</h3>
            {{stdform}}

            <div id="alloc_form">
                <label for="">{{ allocform.type.label }}</label>
                <div class="mt-2" id="id_type">

                        {% for text, val in allocform.fields.type.choices %}
                        <div>
                            <label for="{{ allocform.type.id_for_label}}">
                                <input type="radio" name="{{ allocform.type.html_name }}" value="{{ val }}" required
                                {#{% if kit_alloc.kit.type == val %}checked {% endif %}#}
                                {% if val == type %}checked {% endif %}
                                hx-get="{% url 'kit:update_allocation' kit_alloc.pk %}"
                                hx-trigger="change"
                                hx-target="#alloc_form"
                                hx-select="#alloc_form"
                                hx-include="this"
                                hx-swap="outerHTML">
                                {{ text|capfirst }}
                            </label>
                        </div>
                        {% endfor %}
                    
                </div>

                <div class="form-group">
                    {{ allocform.kit.label }}
                    {{ allocform.kit }}
                </div>

                <div class="form-group">
                    <label for="{{ allocform.kititems.id_for_label}}" class="form-label">{{ allocform.kititems.label }}</label><br>
             
                    <ul>
                    {% for kititem in allocform.fields.kititems.queryset %}
                        <li class="text-center">
                            <input type="checkbox"
                                value="{{ kititem.pk }}"
                                name="{{ allocform.kititems.html_name }}"
                                id="item_id_{{ forloop.counter }}"
                                {% if kititem in allocform.instance.kititems.all %}checked {% elif not kititem.variant.is_stocked %} disabled {% endif %}>
                            <label for="item_id_{{ forloop.counter }}" class="text-center">
                                {% if kititem.variant.photo %}
                                    <figure class="figure m-0 fw-bold">
                                        <img src="{{ kititem.variant.photo.url }}" alt="photo_{{forloop.counter}}" class="figure-img img-fluid rounded m-0">
                                        {% if kititem.variant.is_stocked %} <p class="text-success fw-normal m-0" style="font-size:.7em">In Stock</p>{% else %} <p class="text-danger  fw-normal m-0" style="font-size:.7em">Out Of Stock</p> {% endif %}
                                        <figcaption class="figure-caption text-center  m-0">{{ kititem.variant.name}}</figcaption>
                                    </figure>
                                {% endif %}
                            </label>
                        </li>
                    {% endfor %}
                </ul>

                </div>
            </div>
            <button class="btn btn-danger w-100">Submit</button>
        </form>
    </div>
</div>
{% endblock table %}

kits/templates/kits/allocation_list.html
{% extends "./main.html" %}
{% load static %}




{% block table %}
<div class="d-flex flex-md-row flex-sm-column align-items-center mb-4">
    <div class="">
        <a href="{% url 'kit:allocate_sale' %}" role='button' class="btn btn-primary btn-sm">Allocate And Sale</a>
    </div>

    <form action="" method='GET' class='flex-grow-1 '>
        <div class='searchbar'>
            <input type="text" name='search' class="search-input" placeholder="Roll No, name, year...">
            <button class='search'><i class="fa-solid fa-magnifying-glass" style="color: #ffffff;"></i></button>
        </div>
    </form>
</div>  

{% if kit_allocations %}

    <div>
        <table class="table table-responsive table-sm">
            <thead>
                <tr>
                    <th>Student Name</th>
                    <th>Enrollment</th>
                    <th>Programe</th>
                    <th>Admission Year</th>
                    <th>Kit Name</th>
                    <th>Kit Type</th>
                    <th>Amount Paid</th>
                    <th>Allocated On</th>
                    <th>Last Updated</th>
                    <th class="text-center">Action</th>
                </tr>
            </thead>
            <tbody>
                    {% for kl in kit_allocations %}
                    <tr>
                        <td>{{ kl.student.name }}</td>
                        <td>{{ kl.student.enrollement }}</td>
                        <td>{{ kl.student.program }}</td>
                        <td>{{ kl.student.admission_year }}</td>
                        <td>{{ kl.kit }}</td>
                        <td>{{ kl.kit.type }}</td>
                        <td>{{ kl.total_payment }}</td>
                        <td>{{ kl.created_at }}</td>
                        <td>{{ kl.updated_at }}</td>
                        <td class="d-flex justify-content-center gap-2">
                            <a href="{% url 'kit:allocate_save_detail' kl.pk %}"><i class="fa-solid fa-eye" style="color:#c51315"></i></a>
                            <a href="{% url 'kit:update_allocation' kl.pk %}">Adjust</a>
                        </td>
                    </tr>
                    {% endfor %}
            </tbody>
            <tfoot>
                <div class="d-flex  align-items-center gap-2">
                    <p class=''>Total Records:{{kit_allocations.count}}</p>

                    <p class=''>
                        <a href="{% url 'kit:allocate_list' %}"><i class="fa-solid fa-arrows-rotate" style="color: #1f3251;"></i></a>
                    </p>

                </div>
            </tfoot>
        </table>
    </div>
{% endif %}


{% endblock table %}

kits/templates/kits/kit_form.html
{% extends "./main.html" %}
{% load static %}


{% block page_content %}
<div class="row gap-2">
    <div class="col-md-6 mx-auto p-2 text-light h-100  mx-auto" >
        {% if messages %}
            {% for message in messages %}
                <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
                    {{ message }}
                    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                </div>
            {% endfor %}
        {% endif %}
    
        <form action="{% url 'kit:create_kititems' %}" method="POST" class="p-3 border rounded border-danger">
            {% csrf_token %} 
    
            <h3 style="color:#c51315">Add Kit Items</h3>
            <div class="form-group" id="kit_input_container">
                <label for="" class='form-label text-dark'>How many items you want to add to the kit?</label>
                <input type="number" class="form-control" name='form_count' value='1'>
                <button type='button' class="btn btn-danger mt-3"
                hx-post="{% url 'kit:kititem_form' %}"
                hx-target="#kit_input_container"
                hx-swap="innerHTML"
                >Next</button>
            </div>
        </form>
    </div>

</div>
{% endblock page_content %}

kits/templates/kits/main.html
{% extends "dashboard/home.html" %}
{% load static %}
{% load nav_extras %}

{% block sidenav %}

    {% url 'kit:student_index' as STDINDEX %}
    {% url 'kit:allocate_list' as ALLOCLIST %}
    <ul class="side-navigation ">
        <li><a href="{% url 'kit:student_index' %}" class="{% if '/add-item/' in request.path %}active{% elif '/create-kit/' in request.path %}{% endif %}"><i class="fa-solid fa-gift me-2" style="color: #5d0607ff;"></i>Prepare Kit</a></li>
        <li><a href="{% url 'kit:allocate_list' %}" class="{% if '/list/' in request.path %}active{% endif %}"><i class="fa-solid fa-share-from-square me-2" style="color: #7e080a;"></i>Allocate & Sale</a></li>
    </ul>

{% endblock sidenav %}

{% block table %} 

    {% url 'kit:item_form' as ITEMFORM %}
    {% url 'kit:create_kititems' as KITS %}
    {% url 'catalogue:add_variant' as VARIANT %}


    <div class="d-md-flex gap-2 justify-content-start flex-md-row mb-2">
        <a class="p-2 px-5 btn btn-outline-danger link-underline-opacity-0 rounded rounded-5 mt-2 {% if request.path == ITEMFORM %}active{% endif %}" href="{% url 'kit:item_form' %}" >Kits</a>

        <a class="p-2 px-5 btn btn-outline-danger link-underline-opacity-0 rounded rounded-5 mt-2 {% if request.path == KITS %}active{% endif %}" href="{% url 'kit:create_kititems' %}" >Create kit package</a>

    </div>
    {% block page_content %}
    {% endblock page_content %}
{% endblock table %}

kits/templates/kits/update_kit.html
{% extends "./main.html" %}
{% load static %}
{% load widget_tweaks %}

{% block page_content %}
<div class="row">
    <div class="col-md-6 border border-danger rounded mx-auto py-2">
        <h3 class="text-danger">Update Kit And Items</h3>
        {% if messages %}
            {% for message in messages %}
                <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
                    {{ message }}
                    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                </div>
            {% endfor %}
        {% endif %}

        {% for error in kit_form.non_field_errors %}
            <div class="alert alert-danger alert-dismissible fade show" role="alert">
                ⚠️{{ error }}
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            </div>
        {% endfor %}

        {% if kititems_formset.total_form_count > 0  %}
            <form action="{% url 'kit:update_kit' kit_form.instance.pk %}" class="p-2" method='POST' id="package_edif_form" class="p-0 m-0">
                {{ kititems_formset.management_form }}
                {% csrf_token %}
                {{ kit_form }}

                <div class=" mt-2 p-2  d-flex d-flex justify-content-between bg-danger text-light align-item-center">
                    <p class="m-0">Kit Name</p>
                    <p class="m-0">Item Price</p>
                    <p class="m-0">Item Quantity</p>
                </div>

                {% for form in kititems_formset %}
                    <div class="my-2 d-flex justify-content-between gap-2">{{ form }}
                        {% comment %} <button type="button" class="btn btn-danger rounded rounded-5"
                        hx-get="{% url 'kit:delete_kititem' %}"
                        hx-vals="{'action_type':'save', 'kit':{{kit_form.instance.pk}}, 'kititem':{{form.instance.pk}} }"
                        hx-trigger="click"
                        hx-inclide="this"
                        hx-swap="outerHTML"
                        hx-select="#package_edif_form"
                        hx-target="#package_edif_form">X</button> {% endcomment %}

                        <a href="{% url 'kit:delete_kititem' form.instance.pk %}?kit={{ kit_form.instance.pk }}" class="btn btn-danger rounded rounded-5">X</a>
                    </div>


                {% endfor %}

                <button class="w-100 btn-danger btn">Submit</button>
            </form>
        {% else %}
        <p class="font-monospace text-danger">This kit has no item.</p>
        {% endif %}

    </div>
</div>
{% endblock page_content %}