allocate/urls.py
from django.urls import path
from . import views

app_name = 'allocate'

urlpatterns = [
    path('', views.main_page, name='main'),
    path('list/', views.AllocationView.as_view(), name='allocation_list'),
    path('return/', views.ReturnView.as_view(), name='return_list'),
    path('load-variant/', views.load_variant, name='load_variant'),
    path('update-allocation/<int:pk>/', views.UpdateAllocationView.as_view(), name='update_allocation'), 
    path('return-item/', views.return_item, name='return_item'), 
    path('delete-allocation/', views.delete_allocation, name='delete_allocation'),
    path('products/', views.product_view, name='product_view'),  
    path('products/<int:pk>/', views.product_detail_view, name='product_detail'),
    path('add-item/', views.add_to_allocation_item, name='add_item'),  
    path('cart-items/', views.allocation_cart, name='allocation_cart'),
    path('allocate-items/', views.allocate_items, name="allocate_items"),
    path('allocation-detail/<int:pk>/', views.allocation_detail, name="allocation_detail"),
]

kits/urls.py
from django.urls import path
from . import views

app_name = 'kit'

urlpatterns = [
    path('', views.student_index, name='student_index'),
    path('add-item/', views.CreateItemView.as_view(), name='item_form'),
    path('create-kit/', views.kititem_view, name='create_kititems'),
    path('kititem-form/', views.get_kititem_form, name='kititem_form'),
    path('allocation/list/', views.allocation_list, name="allocate_list"),
    path('allocate-sale/', views.allocate_sale, name="allocate_sale"),
    path('allocate-save/<int:pk>/', views.KitAllocationDetailView.as_view(), name="allocate_save_detail"),
    path('alloccate/update/<int:pk>/', views.UpdateKitAllocation.as_view(), name="update_allocation"),
    path('update/kit/<int:kit_id>/', views.update_kit, name="update_kit"),
    path('delete/kititem/<int:pk>/', views.delete_kititem, name="delete_kititem"),
    path('delete/kit/<int:pk>/', views.delete_kit, name="delete_kit"),
]

stock_management/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', TemplateView.as_view(template_name='index.html'), name='index'),
    path('catalogue/', include('catalogue.urls', namespace='catalogue')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('stock/', include('stock.urls', namespace='stock')),
    path('kit/', include('kits.urls', namespace='kit')),
    path('auth/', include('authapp.urls', namespace='authapp')),
    path('allocate/', include('allocate.urls', namespace='allocate')),
    path('employees/', include('employees.urls', namespace='employees')),



] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

allocate/models.py
from django.db import models


# Create your models here.

allocate/forms.py
from django.forms import ModelForm
from django import forms
from stock.models import Allocations, Returns, Item, Location, ReturnItem
from authapp.models import Employee

class AllocationForm(ModelForm):
    CHOICES_LIST  = [
        (None, '---Select---'),
        (1, 'Employee'),
        (2, 'Location'),
    ]
    item = forms.ModelChoiceField(queryset=Item.objects.all(), widget=forms.Select(attrs={'class': 'form-select my-2'}))
    allocated_to = forms.ChoiceField(choices=CHOICES_LIST, widget=forms.Select(attrs={'class': 'form-select my-2'}))
    name = forms.ChoiceField(choices=[], widget=forms.Select(attrs={'class': 'form-select my-2'}))
    is_serialized = forms.BooleanField(required=False, widget=forms.CheckboxInput(attrs={'class': 'my-3'}), label='Have Serial Number:')

    class Meta:
        model = Allocations
        fields = ['item', 'variants',  'allocated_to', 'name', 'allocated_date', 'is_serialized' ]
        
        widgets = {
            'quantity': forms.NumberInput(attrs={'class': 'form-control my-2', 'min':'1'}),
            'allocated_date': forms.DateInput(attrs={'type': 'date', 'class': 'form-control my-2', 'min': '2023-01-01'}),
            'variant': forms.Select(attrs={'class': 'form-select my-2'}),
        }
        
   
        
    def __init__(self, *args, **kwargs):
        allocated_to = kwargs.pop('allocated_to', None)
        super().__init__(*args, **kwargs)

        if allocated_to == '1':
            self.fields['name'].choices = [
                (p.pk, p.user.full_name) for p in Employee.objects.all()
            ]
        elif allocated_to == '2':
            self.fields['name'].choices = [
                (loc.pk, loc.name) for loc in Location.objects.all()
            ]
        else:
            self.fields['name'].choices = []
        

class ReturnItemForm(ModelForm):
    class Meta:
        model = ReturnItem
        fields = ['variant', 'quantity', 'condition']
        widgets = {
            'variant': forms.Select(attrs={'class': 'form-select'}),
            'quantity': forms.NumberInput(attrs={'class': 'form-control', 'min': 1}),
            'condition': forms.Select(attrs={'class': 'form-select'}),
        }
        

allocate/views.py
from django.shortcuts import render, redirect
from stock.models import(AllocationItem, Category, Stock, Allocations, StockTransactions, Returns, Item, Variant, Location, StockTransactions, Serialnumber, ReturnItem)
from django.views.generic.edit import CreateView, UpdateView
from django.views.generic import ListView
from .forms import AllocationForm, ReturnItemForm
from django.urls import reverse_lazy
from .utils import load_variant_by_item, find_allocation_or_returns
from stock.utils import update_stock_quantity
from django.contrib import messages
from authapp.models import Employee, Student
from django.contrib.contenttypes.models import ContentType
from django.db import transaction
from authapp.decorators import is_manager
from django.db.models import F
from datetime import datetime
from django.utils.decorators import method_decorator
from django.core.paginator import Paginator
from audit.utils import log_action
from django.forms.models import modelformset_factory
from django.contrib.auth.decorators import login_required


# Create your views here.


def main_page(request):
    return redirect('allocate:allocation_list')
class AllocationView(CreateView):
    model = Allocations
    form_class = AllocationForm
    context_object_name = 'allocations'
    template_name = 'allocate/allocation_list.html'
    success_url = reverse_lazy('allocate:allocation_list')
    paginate_by = 2
    
    
    def get_context_data(self, **kwargs):
        context =  super().get_context_data(**kwargs)
        context['allocations'] = Allocations.objects.all()
        paginator = Paginator(context['allocations'], self.paginate_by)
        page_number = self.request.GET.get('page')
        page_obj = paginator.get_page(page_number)
        context['allocations'] = page_obj
        return context
    
    
    def form_valid(self, form ):
        allocation = form.save(commit=False)
        allocation.issued_by = self.request.user
        allocated_to_choice = allocation.allocated_to #type of recipient, i.e Student or Employee
        selected_id = self.request.POST.get('name') #recipient
        
        if allocated_to_choice == 1:
            allocation.contenttype = ContentType.objects.get_for_model(Employee)
        elif allocated_to_choice == 2:
            allocation.contenttype = ContentType.objects.get_for_model(Location)
        else:
            allocation.contenttype = None

        allocation.allocated_to = int(selected_id)
        
        
        msg_text = ''
        with transaction.atomic():
            try:
                stock = Stock.objects.get(variant=allocation.variant)
            except Stock.DoesNotExist:
                msg_text = 'Stock not found'
                messages.error(self.request, msg_text)
                return self.form_invalid(form)
            
            if stock.quantity > 0 and allocation.quantity <= stock.quantity:
                if allocation.variant.is_serialized:
                    serial_number = self.request.POST.get('serial_number')
                    serial_number_obj = Serialnumber.objects.filter(serial_number__iexact=serial_number).first()
                    
                    if serial_number_obj.status and serial_number_obj.status != Serialnumber.NS:
                        msg_text = f'{serial_number} is already allocated'
                        messages.error(self.request, msg_text)
                        return self.form_invalid(form)
                        
                    if serial_number_obj.status == Serialnumber.NS and allocation.quantity > 1:
                        msg_text = 'Only one serial number is allowed'
                        messages.error(self.request, msg_text)
                        return self.form_invalid(form)
                    
                    serial_number_obj.status = Serialnumber.AL
                    serial_number_obj.content_type = allocation.contenttype
                    serial_number_obj.object_id = allocation.allocated_to
                    serial_number_obj.save()
                    target = serial_number_obj.content_type.get_object_for_this_type(id=serial_number_obj.object_id)
                    msg_text = f'{serial_number} is allocated to {target} successfully'
                    
                allocation.save()
                transation = StockTransactions.objects.create(
                    variant = allocation.variant,
                    txn_type = StockTransactions.OT,
                    quantity = allocation.quantity,
                    created_by = self.request.user,
                    contenttype = allocation.contenttype,
                    reference = allocation.allocated_to
                )
                if not allocation.variant.is_serialized:
                    stock = update_stock_quantity(self.request, item_id = allocation.variant.id, quantity = -allocation.quantity)
                    stock.movement_type = Stock.OT
                    stock.save()
                    
                if msg_text:
                    messages.success(self.request, msg_text)
                messages.success(self.request, f'{allocation.variant} allocated successfully')    
                return super().form_valid(form )
            messages.error(self.request, 'Out of stock. Only {} available'.format(stock.quantity))
            return self.form_invalid(form)
        
        return super().form_valid(form )
    
    def form_invalid(self, form):
        response = super().form_invalid(form)
        return response
    
     
    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        allocated_to = self.request.POST.get('allocated_to') or self.request.GET.get('allocated_to')
        if allocated_to:
            kwargs['allocated_to'] = allocated_to
        return kwargs
    
    def get(self, request, *args, **kwargs):
        self.object = None
        if request.headers.get('hx-request'):
            item = request.GET.get('item')
            variant = request.GET.get('variant')
            allocated_to = request.GET.get('allocated_to')
            is_serialized = request.GET.get('is_serialized')
                       
            initial = {
                'variant': variant,
            }
            
            context = self.get_context_data(**kwargs)
            form = self.form_class(initial=initial, allocated_to=allocated_to)
            
            if is_serialized == 'on':
                serial_number = request.GET.get('serial_number')
                context['serial_number'] = serial_number
                form.fields['is_serialized'].initial = True
                
            context['item_id'] = item
            context['alloc_id'] = request.GET.get('allocated_to')
            context['form'] = form
            
            return render(request, self.template_name, context)

        if request.GET.get('search'):
            search_text = request.GET.get('search').strip().lower()
            context = self.get_context_data(**kwargs)
            form = self.form_class()
            allocations = find_allocation_or_returns(search_text, search_model = self.model)
            context['form'] = form
            context['allocations'] = allocations
            paginator = Paginator(context['allocations'], self.paginate_by)
            page_number = self.request.GET.get('page')
            page_obj = paginator.get_page(page_number)
            context['allocations'] = page_obj


            return render(request, self.template_name, context)
        
        return super().get(request, *args, **kwargs)



class UpdateAllocationView(UpdateView):
    model = Allocations
    form_class = AllocationForm
    context_object_name = 'allocations'
    template_name = 'allocate/allocation_update.html'
    
    
    def form_valid(self, form):
        instance = form.save(commit=False)
        serial_number = self.request.POST.get('serial_number')
        is_serialized = self.request.POST.get('is_serialized')
        if is_serialized == 'on' and serial_number:
            if instance.quantity > 1 or instance.quantity < 1:
                messages.error(self.request, 'Only one serial number is allowed.')
                return self.get(self.request, *self.args, **self.kwargs)
            
        
        if self.request.POST.get('allocated_to') == '1':
            instance.contenttype = ContentType.objects.get_for_model(Employee)
            print('contenttype after', instance.contenttype)

        elif self.request.POST.get('allocated_to') == '2':
            instance.contenttype = ContentType.objects.get_for_model(Location)
            print('contenttype after', instance.contenttype)

        print('data',form.cleaned_data)
        self.success_url = reverse_lazy('allocate:update_allocation', kwargs={'pk': self.kwargs['pk']})
        messages.success(self.request, 'Allocation updated successfully')
        form.save()
        return super().form_valid(form)
    
    
    def get(self, request, *args, **kwargs):
        self.object = None
        instance = self.get_object()
        context = self.get_context_data(**kwargs)
        alloc_id = request.GET.get('allocated_to')
        
        
        
        try:
            serial_number_obj = Serialnumber.objects.get(product_variant=instance.variant, status=Serialnumber.AL)
        except Serialnumber.DoesNotExist:
            serial_number_obj = None
            messages.error(request, 'Serial number not found for this item')
        
        if instance.contenttype.pk == 27:
            context['alloc_id'] = alloc_id if alloc_id else 1
        elif instance.contenttype.pk == 7:
            context['alloc_id'] = alloc_id if alloc_id else 2
        else:
            context['alloc_id'] = alloc_id if alloc_id else 0
        
        form = self.form_class(instance=instance,  allocated_to=str(context['alloc_id']))
        
        if request.GET.get('allocated_to') == '1':

allocate/templates/allocate/allocation_detail.html
{% extends "allocate/product_view.html" %}
{% load static %}


{% block product %}
{% if items_allocated %}

<ul class="list-group w-25">
    <li class="list-group-item"><strong>Recipient Details</strong></li>

    <li class="list-group-item d-flex justify-content-between">
        <div class="">Name</div>
        <div>{{allocation.get_recipient|title}}</div>
    </li>

    <li class="list-group-item d-flex justify-content-between">
        <div class="text-capitalize">Employee id</div>
        <div>{{allocation.get_recipient.emp_id|upper}}</div>
    </li>

    <li class="list-group-item d-flex justify-content-between">
        <div class="text-capitalize">Department Location</div>
        <div>{{allocation.location|title}}</div>
    </li>

    <li class="list-group-item d-flex justify-content-between">
        <div class="text-capitalize"><strong>Item Name</strong></div>
        <div class="text-capitalize"><strong>Qauntity</strong></div>
    </li>

    {% for item in items_allocated %}
    <li class="list-group-item d-flex justify-content-between">
        <div class="text-capitalize"> {{ item.variant.name }}
            {% if item.variant.is_serialized %} ({{item.variant.get_serial_number}}) {% endif %}
        </div>
        <div>{{ item.quantity }}</div>
    </li>
    {% endfor %}

    <li class="list-group-item d-flex justify-content-start gap-2">
        <button type="button" class="btn btn-sm btn-primary" onclick="window.history.back()">Back</button>
        <button type="button" class="btn btn-sm btn-danger" data-bs-target="#return_form_modal" data-bs-toggle="modal">Return </button>
    </li>

</ul>
{% endif %}

<div class="modal fade" tabindex="-1" data-bs-backdrop="static" data-bs-keyboard="false"  id='return_form_modal'>
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h3 class="modal-title">Return Items</h3>
            </div>
            <div class="modal-body">
                <form action="{% url 'allocate:allocation_detail' allocation.id %}" method="POST" id='return_form'>
                    {% csrf_token %}
                    <div class="d-flex justify-content-between">
                        <div class="flex-item ms-5 mb-2 text-capitalize fw-bold">Item</div>
                        <div class="flex-item me-5 mb-2 text-capitalize fw-bold">Status</div>
                    </div>

                  {% for item in items_allocated %}

                  <div class="d-flex justify-content-between">

                      <div class="form-check">
                            <input class="" type="checkbox" name='items' value="{{item.variant.id}}" id="id_{{item.variant}}">
                            <label class="form-check-label" for="id_{{item.variant}}">
                               {{item.variant.name|title}}
                            </label>
                        </div>
                        <div>
                           <select name="status" class="form-select">
                                <option value="" selected>--select--</option>
                                {% for value, label in status_list %}
                                    <option value="{{ value }}">{{ label }}</option>
                                {% endfor %}
                            </select>

                        </div>
                  </div>


                  {% endfor %}
                </form>
            </div>
            <div class="modal-footer">
                <button class="btn btn-sm btn-danger" type="button" data-bs-dismiss='modal' data-bs-target='#return_form_modal'>Cancel</button>
                <button class="btn btn-sm btn-success" type="submit" form="return_form">Submit</button>
            </div>
        </div>
    </div>
</div>

{% endblock %}

allocate/templates/allocate/allocation_update.html
{% extends "allocate/main.html" %}
{% load partials %}
{% load static %}

{% block page_content %}

<div class="w-50 mx-auto">
    
    <div class="message-body">
        {% if messages %}
            {% for message in messages %}
                <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
                    {{ message }}
                    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                </div>
            {% endfor %}
        {% endif %}
    </div>

    {% startpartial optionpart %}
    <div class="form-group" id="productoptions">
            {{ form.variant.label_tag }}
            {{ form.variant }}
    </div>
    {% endpartial %}

    <form action="" method='POST' id='allocation_form' style="background:#c51315" class="p-3 text-light">
    <h3>Update Allocation</h3>

    {% csrf_token %}



    <div class="form-group">
    {{ form.item.label_tag }}
    <select name="{{ form.item.html_name }}" class='form-select mt-1'
    hx-get="{% url 'allocate:load_variant' %}"
    hx-swap="outerHTML"
    hx-trigger="change"
    hx-target="#productoptions"
    required>
        {% for val, text in form.item.field.choices %}
            <option value="{{ val }}" {% if val|stringformat:"s" == item_id|stringformat:"s" %}selected{% endif %}>
                {{ text }}
            </option>
        {% endfor %}                
    </select>
        </div>

    {% partial optionpart %}

    <div class="form-gourp">
        {{ form.is_serialized }}
        {{ form.is_serialized.label_tag }}
    </div>

    <div id="serial_container" class="form-group">
        {% if serial_number %}
        <input type="text" class="form-control" placeholder="Serial Number" name='serial_number' value="{{serial_number}}" required>
        {% endif %}
    </div>

    <div class="form-gourp">
        {{ form.allocated_to.label_tag }}
        <select name="{{ form.allocated_to.html_name }}" class='form-select mt-1'
        id='allocate_to'
        hx-get="{% url 'allocate:update_allocation' form.instance.pk %}"
        hx-swap="outerHTML"
        hx-trigger="change"
        hx-target="#allocation_form"
        hx-include="#allocation_form"
        hx-select="#allocation_form"
        required>
            {% for val, text in form.allocated_to.field.choices %}
                <option value="{{ val }}" {% if val|stringformat:"s" == alloc_id|stringformat:"s" %}selected{% endif %}>
                    {{ text }}
                </option>
            {% endfor %}                
        </select>
    </div>

    <div class="form-gourp">
        {{ form.name.label_tag }}
        {#<input type="text" name='name' class='form-control' value="{{  }}" require>#}
        
        <select name="{{ form.name.html_name }}" id="" class="form-select">
            {% for val, text in form.name.field.choices %}
                <option value="{{ val }}" {% if val|stringformat:"s" == recipient_id|stringformat:"s" %}selected{% endif %}>{{ text }}</option>
            {% endfor %}
        </select>
    </div>

    <div class="form-gourp">
        {{ form.quantity.label_tag }}
        {{ form.quantity }}
    </div>

    <div class="form-gourp">
        {{ form.allocated_date.label_tag }}
        {{ form.allocated_date }}
    </div>

                    
    <div class="modal-footer d-flex justify-content-center gap-3">
        <a href="{% url 'allocate:allocation_list' %}" role="button" class="btn btn-danger">Cancel</a>
        <button type="submit" class="btn btn-primary" form='allocation_form'>Submit</button>
    </div>


</form>
</div>

{% endblock%}

allocate/templates/allocate/cart.html
{% extends "dashboard/home.html" %}
{% load static %}


{% block table %}


{% if variants %}
<div class="container">
    <div class="row justify-content-center align-items-center  p-3 mb-2">
        <div class="col col-lg-4">
            
            <form action="{% url 'allocate:allocate_items' %}" id="allocation_form" method='POST'>
                {% csrf_token %}
                <div class="form-group m-1">
                    <select name="location" id="" class="form-select" required>
                        <option value="" selected>--Select Recipient Type--</option>
                        {% for loc in locations %}
                            <option value="{{loc.id}}">{{loc.name}}</option>
                        {% endfor %}
                    </select>
                </div>

                <div class="form-group m-1">
                    <select name="employee" id="" class="form-select" required>
                        <option value="" selected>--Select Recipient--</option>
                        {% for emp in employees %}
                            <option value="{{emp.id}}">{{emp.user.full_name}}</option>
                        {% endfor %}
                    </select>
                </div>

                <ul class='list-group'>
                    {% for variant in variants %}
                        <li class="list-group-item d-flex justify-content-between m-1  p-2 gap-3 cart-item">
                            <strong class="flex-item flex-grow-1">{{forloop.counter}}. {{variant.name|title}}</strong>
                            
                            <a href="{% url 'allocate:allocation_cart' %}?id={{variant.id}}"><i class="fa-solid fa-trash" style="color: #ff0000;"></i></a>
                        </li>
                    {% endfor %}
                </ul>
            </form>

            <div class="text-center">

                <button type="button" class="btn btn-sm btn-primary" data-bs-target='#id_confirm_allocation' data-bs-toggle='modal' >Allocate</button>
            </div>
        </div>
    </div>
</div>


<div class="modal fade" tabindex="1" id="id_confirm_allocation" data-bs-backdrop="static" data-bs-keyboard="false" >
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h3 class="model-title">Confirm</h3>
                
            </div>
            <div class="modal-body">Are you sure you want to allocate.</div>
            <div class="modal-footer d-flex justify-content-end gap-2">
                <button type="button" class="btn btn-sm btn-danger" data-bs-dismiss="modal">Cancel</button>
                <button type='submit' class="btn btn-sm btn-success" form="allocation_form">Confirm</button>
            </div>
        </div>
    </div>
</div>
{% else %}
<h3>Please select an item to allocate</h3>
{% endif %}

{% endblock %}

allocate/templates/allocate/main.html
{% extends "dashboard/home.html" %}

{% block table %}

    {% block tabs %}
        {% url 'allocate:allocation_list' as ALLOCATION %}
        {% url 'allocate:return_list' as RETURN %}
    {% endblock tabs %}


<div class="d-md-flex gap-2 justify-content-start flex-md-row mb-2">
    <a class="p-2 px-5 btn btn-outline-danger link-underline-opacity-0 rounded rounded-5 mt-2 {% if request.path == ALLOCATION %}active{% endif %}" href="{% url 'allocate:allocation_list' %}" >Allocation Records</a>

    <a class="p-2 px-5 btn btn-outline-danger link-underline-opacity-0 rounded rounded-5 mt-2 {% if request.path == RETURN %}active{% endif %}" href="{% url 'allocate:return_list' %}" >Return</a>

</div>


    {% block page_content %}{% endblock page_content %}
{% endblock table %}

allocate/templates/allocate/product_view.html
{% extends "dashboard/home.html" %}
{% load static %}


{% block table %}

    <div class="message-body">
        {% if messages %}
            {% for message in messages %}
                <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
                    {{ message }}
                    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                </div>
            {% endfor %}
        {% endif %}
    </div>
    
    <div class="wrapper">
        <ul class="tab-box">
            <div class="arrows"><i class="fa-solid fa-angle-left" id='left' style="color: #3f4163;"></i></div>

            <li class="text-capitalize tab">
                <a href="{% url 'allocate:product_view' %}" class="link link-underline-opacity-0 link-light">All</a>
            </li>
            {% for category in categories %}
            
            <li class="text-capitalize tab">
                <a href="{% url 'allocate:product_view' %}?category={{category.id}}" class="link link-underline-opacity-0 link-light">{{category}}</a>
            </li>

        
            {% endfor %}
            <div class="arrows"><i class="fa-solid fa-angle-right" id='right' style="color: #3f4163;"></i></div>

        </ul>
    </div>

    {% block product %}

    <div class="container">
        <div class="row gap-2">
            <div class="col-12 mb-2">

                <button type="button" class="btn btn-sm btn-primary mb-2" onclick="window.history.back()">Back</button>
            </div>
            {% for item in items %}

                <div class="product col col-md-2 col-xxl-2 col-lg-2">

                    <div class="card shadow">
                        {% with v=item.variant.all|first %}
                            {% if v and v.photo %}
                                <img src="{{ v.photo.url }}" class="card-img-top img-fluid" alt="{{item}}">
                            {% else %}
                                <img src="{% static 'allocate/default.png' %}" alt="img" class="card-img-top img-fluid">
                            {% endif %}
                        {% endwith %}
                        <div class="card-body">
                            <h5 class="card-title">{{item}}</h5>
                            <h6><a href="{% if item.get_total_of_variant > 0 %} {% url 'allocate:product_detail' item.id %} {% else %}# {% endif %}" alt="{{item}}" role='button' class="link link-underline-opacity-0 text-capitalize card-link stretched-link {% if item.get_total_of_variant > 0 %} link-success {% else %} link-danger {% endif %}">total Quantity: {{item.get_total_of_variant}}</a></h6>
                        </div>
                    </div>
                </div>
             
            {% endfor %}
        </div>
    </div>

    {% endblock  %}
{% endblock %}

allocate/templates/allocate/return_list.html
{% extends "allocate/main.html" %}

{% block page_content %}
<form action="{% url 'allocate:return_list' %}" method='GET' class='flex-grow-1'>
    <div class='searchbar'>
        <input type="text" name='search' class="search-input" placeholder="Recipient name...">
        <button class='search'><i class="fa-solid fa-magnifying-glass" style="color: #ffffff;"></i></button>
    </div>
</form>

{% if returns %}

<table class="table table-sm table responsive">
    <thead>
        <tr>
            <th>Item</th>
            <th>Returned From</th>
            <th>Collected By</th>
            <th>Returned On</th>
        </tr>
    </thead>
    <tbody>
        {% for rn in returns  %}
        <tr class="
            {% if rn.condition == 'good' %} table-success
            {% elif rn.condition == 'damaged' %} table-danger
            {% else %} table-warning
            {% endif %}">
            
            <td class="item-cell">
                {{ rn.get_returned_items }}
                <i class="fa-sharp fa-solid fa-caret-down"></i>

                <div class="item-detail-box">
                   <pre>Name &nbsp; &nbsp; &nbsp; Condition</pre> 
                    {% for item in rn.returnitem_set.all %}
                    <pre>{{ item.variant }}&nbsp; &nbsp; &nbsp;  {{ item.get_condition_display }}</pre><br>
                    {% endfor %}
                </div>
            </td>

            <td>{{ rn.allocation.content_object }}</td>
            <td class="fw-bold">{{ rn.returned_by }}
                <p style="font-size:.8em;" class='text-info fw-normal'>{{ rn.returned_by.full_name }}</p>
            </td>
          
            <td class="fw-bold">{{ rn.return_date|date:'d-m-Y' }}
               <p style="font-size:.8em;" class='text-danger fw-normal'>{{ rn.return_date|time:"H:i:s" }}</p>
            </td>
        </tr>
        {% endfor %}
    </tbody>
    <tfoot></tfoot>
</table>
{% endif %}
{% endblock page_content %}