allocate/urls.py
from django.urls import path
from . import views

app_name = 'allocate'

urlpatterns = [
    path('', views.main_page, name='main'),
    path('list/', views.AllocationView.as_view(), name='allocation_list'),
    path('return/', views.ReturnView.as_view(), name='return_list'),
    path('load-variant/', views.load_variant, name='load_variant'),
    path('update-allocation/<int:pk>/', views.UpdateAllocationView.as_view(), name='update_allocation'), 
    path('return-item/', views.return_item, name='return_item'), 
    path('delete-allocation/', views.delete_allocation, name='delete_allocation'),
    path('products/', views.product_view, name='product_view'),  
    path('products/<int:pk>/', views.product_detail_view, name='product_detail'),
    path('add-item/', views.add_to_allocation_item, name='add_item'),  
    path('cart-items/', views.allocation_cart, name='allocation_cart'),
    path('allocate-items/', views.allocate_items, name="allocate_items"),
    path('allocation-detail/<int:pk>/', views.allocation_detail, name="allocation_detail"),
]

kits/urls.py
from django.urls import path
from . import views

app_name = 'kit'

urlpatterns = [
    path('', views.student_index, name='student_index'),
    path('add-item/', views.CreateItemView.as_view(), name='item_form'),
    path('create-kit/', views.kititem_view, name='create_kititems'),
    path('kititem-form/', views.get_kititem_form, name='kititem_form'),
    path('allocation/list/', views.allocation_list, name="allocate_list"),
    path('allocate-sale/', views.allocate_sale, name="allocate_sale"),
    path('allocate-save/<int:pk>/', views.KitAllocationDetailView.as_view(), name="allocate_save_detail"),
    path('alloccate/update/<int:pk>/', views.UpdateKitAllocation.as_view(), name="update_allocation"),
    path('update/kit/<int:kit_id>/', views.update_kit, name="update_kit"),
    path('delete/kititem/<int:pk>/', views.delete_kititem, name="delete_kititem"),
    path('delete/kit/<int:pk>/', views.delete_kit, name="delete_kit"),
]

orders/urls.py
from django.urls import path
from . import views

app_name = 'orders'

urlpatterns = [
    path('', views.main, name="main"),
    path('order-list/', views.OrdersCreateView.as_view(), name="order_list"),
    path('purchase/list/', views.CreatePurchase.as_view(), name='purchase_list'),
    path('load-variant/', views.load_variant_by_item, name='load_variant'),

    path('invoice-list/', views.CreateInvoice.as_view(), name="invoice_list"),
    path('page-3/', views.page_three, name="page_three"),
    
]

stock/urls.py
from django.urls import path
from . import views
from .forms import (ItemForm, CategoryForm, VariantForm
)
app_name = 'stock'

urlpatterns = [


    path('', views.StockCreate.as_view(), name='create_stock'),
    path('item-detail/<int:pk>/', views.ItemDetailView.as_view(), name='item_detail'),
    path('category-product/', views.load_product_by_category, name='category_product'),
    path('item-variant/', views.load_variant_by_item, name='item_variant'),
    path('item/update/<int:pk>/', views.ItemUpdateView.as_view(), name = 'update_item'),
    path('transaction-list/', views.StockTransactionList.as_view(), name='transaction_list'),
    path('stock/add-success', views.add_success_view, name='add_success'),
    


    path('purchase/<int:pk>/', views.PurchaseDetailView.as_view(), name='purchase_detail'),

    path('issue/list/', views.IssueListView.as_view(), name='kit_list'),
    path('issue/list/<int:pk>/', views.IssueDetailView.as_view(), name='kit_detail'),

    
    path('find/student/', views.filter_student, name='filter_student'),
    
    path('student/list/', views.StudentListView.as_view(), name='student_list'),
    
    path('download/sample/', views.sample_excel, name='sample_excel'),
    
    
    path('issue-new-kit/', views.issue_new_kit, name='issue_new_kit'),
    
    path('exchange-kit/', views.exchage_kit, name='exchange_kit'),

    

]



vendor_urlpatterns = [
    path('vendor/list/', views.VendorsCreateView.as_view(), name='vendor_list'),
]

edit_urlpatterns = [
    path('<int:pk>/edit/', views.edit_stock, name='edit_stock'),
    path('stock-detail/<int:pk>/', views.stock_detail, name='stock_detail'),
    path('serial-detail/<int:pk>/', views.serial_detail, name='serial_detail'),
    path('edit-serial/<int:pk>/', views.edit_serial, name='edit_serial'),
    path('<int:pk>/', views.edit_stock_with_serials, name='edit_stock_with_serials'),
    path('update-serial-number/<int:pk>/', views.UpdateSerialNumber.as_view(), name='update_serial_number'),
    path('update-stock/<int:pk>/', views.UpdateStock.as_view(), name='update_stock'),
]

htmx_urlpatterns = [
    path('check-serializable/', views.check_serializable_view, name='check_serializable'),
    path('add-serial/', views.add_serial_view, name='add_serial'),
    path('remove-input/', views.remove_input_view, name='remove_input'),
]


urlpatterns += htmx_urlpatterns
urlpatterns += edit_urlpatterns
urlpatterns += vendor_urlpatterns

stock_management/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', TemplateView.as_view(template_name='index.html'), name='index'),
    path('catalogue/', include('catalogue.urls', namespace='catalogue')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('stock/', include('stock.urls', namespace='stock')),
    path('kit/', include('kits.urls', namespace='kit')),
    path('auth/', include('authapp.urls', namespace='authapp')),
    path('allocate/', include('allocate.urls', namespace='allocate')),
    path('employees/', include('employees.urls', namespace='employees')),



] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

stock/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import JsonResponse
from django.urls import reverse_lazy
from django.views.generic.edit import CreateView, UpdateView, DeleteView, FormView
from django.contrib import messages

from django.views.generic import ListView, DetailView, FormView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from stock.utils import *
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse, HttpResponseRedirect, QueryDict
from datetime import date, timedelta
from django.db.models import Q
from django.forms import inlineformset_factory, formset_factory
from django.db import transaction, IntegrityError
from django.utils.safestring import mark_safe
from django.db.models import F
from django.core.paginator import Paginator
from django.views.generic.edit import FormMixin
from .models import *
from django.utils.decorators import method_decorator
from authapp.decorators import is_manager
from .forms import *
from audit.utils import log_action

# from template_partials.shortcuts import render_partial
import json




PAGINATED_BY = 10

@method_decorator(is_manager, name='dispatch')
@method_decorator(login_required, name='dispatch')
class VendorsCreateView(CreateView):
    model = Vendor
    template_name = 'stock/vendor/vendor_list.html'
    context_object_name = 'vendors'
    form_class = VendorForm
    success_url = reverse_lazy('stock:vendor_list')
    
    def get_context_data(self, **kwargs):
        vendors = Vendor.objects.all()
        context =  super().get_context_data(**kwargs)
        context['vendors'] = vendors
        return context
    
    def form_valid(self, form):
        obj = form.save()
        messages.success(self.request, 'Vendor added successfully')
        log_action(self.request.user, request=self.request, action = 'Created vendor', instance=obj)    
        return super().form_valid(form)
    
    def form_invalid(self, form):
        response = super().form_invalid(form)
        return response
    
    
def add_success_view(request):
    return render(request, 'stock/add_success.html') 
        


@method_decorator(is_manager, name='dispatch')
class StockCreate(CreateView):
    model = Stock
    context_object_name = 'stocks'
    template_name = 'stock/create_stock.html'
    form_class = StockForm
    success_url = reverse_lazy('stock:create_stock')
    paginate_by = PAGINATED_BY
    

    
    def form_valid(self, form):
        stock = form.save(commit=False)
        item = form.instance.variant.product
        variant = form.instance.variant
        stock.user = self.request.user
        
        in_stock = Stock.objects.filter(variant=stock.variant, location=stock.location, variant__product=item).first()
        
        if in_stock and not variant.is_serialized and not self.request.POST.get("confirm"):
            if self.request.headers.get('hx-request'):
                form_data = self.request.POST
                stock_data = {
                    'location': Location.objects.get(pk = form_data.get('location')),
                    'variant': Variant.objects.get(pk=form_data.get('variant')),
                    'quantity': int(form_data.get('quantity')) + in_stock.quantity,
                }
                return render(self.request, 'partials/confirm_stock.html', {'stock': in_stock, 'message': 'Stock already exist', 'class': 'text-danger', 'form_data': self.request.POST, 'stock_data': stock_data})
            
        if in_stock and not variant.is_serialized and self.request.POST.get("confirm"):
            if self.request.headers.get('hx-request'):
                form = StockForm(self.request.POST, instance=in_stock)
                in_stock.quantity += int(self.request.POST.get('quantity'))
                
                with transaction.atomic():
                    stock = in_stock.save()
                    log_action(self.request.user, request=self.request, action = 'Updated stock', instance=in_stock)
                    StockTransactions.objects.create(
                        variant= in_stock.variant,
                        quantity = int(self.request.POST.get('quantity')),
                        txn_type = StockTransactions.AD,
                        created_by = self.request.user,
                        contenttype =  ContentType.objects.get_for_model(Stock),
                        reference = in_stock.pk
                    )
                messages.success(self.request, "Stock updated successfully")
                return render(self.request, "partials/stock_detail.html", {"stock": stock})
        else:
            if self.request.headers.get('hx-request'):
                serial_number = self.request.POST.getlist('serial')
                if serial_number:
                    serialnumber_obj = Serialnumber.objects.filter(serial_number__in=serial_number)
                    
                    if serialnumber_obj.exists():
                        messages.error(self.request, f'Below serial numbers already exists')
                        return render(self.request, 'partials/stock_detail.html', {'serialnumber_obj': serialnumber_obj, 'class': 'text-danger'})
                    else:
                       try: 
                        with transaction.atomic():
                            if in_stock:
                                stock = in_stock
                            else:
                                stock = form.save()
                            created_serials = []
                            for serial in serial_number:
                                try:
                                    sn = Serialnumber.objects.create(
                                        item=item,
                                        product_variant=stock.variant,
                                        serial_number=serial
                                    )
                                    
                                    created_serials.append(sn)
                                    # increment quantity atomically
                                    Stock.objects.filter(id=stock.id).update(quantity=F('quantity') + 1)
                                    log_action(self.request.user, request=self.request, action = 'Created serial number', instance=sn)
                                except IntegrityError:
                                    messages.warning(self.request, f"⚠️ Serial number '{serial.strip()}' is duplicate and not allowed. Try again.")
                                    return render (self.request, 'partials/stock_detail.html', {'class': 'text-danger'})
                            StockTransactions.objects.create(
                                variant= stock.variant,
                                quantity = len(created_serials),
                                txn_type = StockTransactions.IN,
                                created_by = self.request.user,
                                contenttype =  ContentType.objects.get_for_model(Stock),
                                reference = stock.pk
                            )     
                            stock.refresh_from_db()
                            
                            if created_serials:
                                messages.success(self.request, f'Total {len(created_serials)} serial numbers added successfully')
                                sr_object = Serialnumber.objects.filter(serial_number__in=serial_number)
                            
                            context = {'class': 'text-success', 'serialnumber_obj': sr_object}
                            response =  render(self.request, 'partials/stock_detail.html', context)
                            response['HX-Target'] = '#response_message'
                            return response
                       except Exception as e:
                            messages.error(self.request, f'Error: {str(e)}')
                            return render(self.request, 'partials/stock_detail.html', {'class': 'text-danger'})
                else:
                    with transaction.atomic():
                        stock = form.save(commit=False)
                        stock.movement_type = Stock.IN
                        stock.save()
                        log_action(self.request.user, request=self.request, action = 'Created stock', instance=stock)
                        StockTransactions.objects.create(
                            variant= stock.variant,
                            quantity = stock.quantity,
                            txn_type = StockTransactions.IN,
                            created_by = self.request.user,
                            contenttype =  ContentType.objects.get_for_model(Stock),
                            reference = stock.pk
                        )
                    message = f'Stock added successfully'
                    context = {'stock': stock, 'message': message, 'class': 'text-success'}
                    response =  render(self.request, 'partials/stock_detail.html', context)
                    response['HX-Target'] = '#response_message'
                    return response
    
    def form_invalid(self, form):
        if self.request.headers.get('hx-request'):
            print('invalid')
            item = form.cleaned_data['variant']
            variant = form.cleaned_data['variant']
            location = form.cleaned_data['location']
            stock = Stock.objects.filter(variant=variant.pk, location=location.pk).first()
            message = "Stock already exists"
            context = {'stock': stock, 'message': message, 'class': 'text-danger'}
            response = render(self.request, 'partials/stock_detail.html', context)
            response['HX-Target'] = '#response_message'
            return response
        

templates/stock/add_success.html
{% extends 'dashboard/home.html' %}
{% load static %}

{% block table %}
    <div class="container">
        <div class="row align-items-center">
            <div class="col text-center mx-auto mt-5">
            {% if messages %}
            {% for message in messages %}
                <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
                    {{ message }}
                    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                </div>
            {% endfor %}
            {% endif %}
                <div class="d-flex flex-md-row">
                    <a class='btn btn-warning me-2' href="{% url 'stock:purchase_list' %}">Back</a>
                    <a class='btn btn-primary me-2' href="{% url 'stock:add_item' %}">Add More</a>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/stock/create_stock.html
{% extends "dashboard/home.html" %}
{% load static %}
{% load partials %}
{% load paginator_tag %}

{% block table %}

{% url 'stock:transaction_list' as TRANSACTION %}
{% url 'stock:create_stock' as STOCK %}


<div id="stock_add_form_container"></div>

    <div class="message-body">
        {% if messages %}
            {% for message in messages %}
                <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
                    {{ message }}
                    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                </div>
            {% endfor %}
        {% endif %}
    </div>

<div class="modal fade" id="id_stockform_modal" tabindex="-1" data-bs-backdrop="static">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <h3 class="modal-title">Add Stock</h3>
            </div>
            <div class="modal-body">
                {% startpartial optionpart %}
                <div class="form-group" id="productoptions">
                    <select name="{{form.variant.html_name}}" id="" class='form-select'
                    hx-get="{% url 'stock:check_serializable' %}"
                    hx-swap="innerHTML"
                    hx-include='this'
                    hx-select="#serial_number_form_container"
                    required>
                        {% for val, text in form.variant.field.choices %}
                            <option value="{{val}}">{{text}}</option>
                        {% endfor %}                
                    </select>
                </div>
                {% endpartial %}

                <form hx-post="{% url 'stock:create_stock' %}" hx-target="#response_message" hx-swap="innerHTML" id="stock_form">
                    {% csrf_token %} 

                    <table class="table table-responsize table-sm caption-top">
                    <thead>
                        <tr>
                            <th>Item</th>
                            <th>Location</th>
                            <th>Variant</th>
                        </tr>
                    </thead>

                    <tbody>

                        {% for error in form.non_field_errors %}
                            <p class="bg-danger-subtle rounded text-danger">⚠️{{ error }}</p>
                        {% endfor %}

                        <td>
                            <div class="form-group">
                                <select name="{{form.item.html_name}}" class='form-select'
                                hx-get="{% url 'stock:item_variant' %}"
                                hx-swap="outerHTML"
                                hx-trigger="change"
                                hx-target="#productoptions"
                                required>
                                    {% for val, text in form.item.field.choices %}
                                        <option value="{{val}}">{{text}}</option>
                                    {% endfor %}                
                                </select>
                            </div>
                        </td>

                        <td>

                            <div class="form-group">
                                {{form.location}}
                            </div>
                        </td>

                        <td>
                            {% partial optionpart %}
                        </td>

                        <td id="quantity_or_serial">

                            {% comment %} <div class="form-group" >
                                {{form.quantity}}
                            </div> {% endcomment %}
                        </td>
                        
                    </tbody>

                    </table>

                    <tfoot>
                        <div id="serial_number_container"></div>
                    </tfoot>
                    <div id="response_message"></div>
                </form>


            </div>

            <div class="modal-footer d-flex justify-content-center gap-3">
                <button type="button" class="btn btn-danger" data-bs-dismiss='modal'>Cancel</button>
                <button type="submit" class="btn btn-primary" form='stock_form'>Submit</button>
            </div>
        </div>
    </div>
</div>


<div>
    <div class="d-md-flex gap-2 justify-content-start flex-md-row mb-2">
        <a class="p-2  btn btn-outline-danger link-underline-opacity-0 rounded rounded-5 mt-2 {% if request.path == STOCK %}active{% endif %}" href="{% url 'stock:create_stock' %}" style="width:10rem">Stock</a>

        <a class="p-2  btn btn-outline-danger link-underline-opacity-0 rounded rounded-5 mt-2 {% if request.path == TRANSACTION %}active{% endif %}" href="{% url 'stock:transaction_list' %}" style="width:10rem">Transations</a>

    </div>

    <div class="d-flex gap-2 align-items-center justify-content-between">


        <div class="add">
            <button type="button" class="btn btn-sm btn-primary" data-bs-target='#id_stockform_modal' data-bs-toggle='modal'>Add Stock</button>
        </div>
        
        {% if stocks %}
            <div class=''>
                <form action="" method='POST'>
                    {% csrf_token %}
                    <button class="btn btn-sm btn-secondary">Download</button>
                </form>
            </div>
        
        {% endif %}
        <form action="" method='GET' class='flex-grow-1'>
            <div class='searchbar'>
                <input type="text" name='search' class="search-input" placeholder="Variant name...">
                <button class='search'><i class="fa-solid fa-magnifying-glass"></i></button>
            </div>
        </form>



    </div>

    {% if stocks %}
    
        <table class="table table-responsive table-sm table-responsive">
            <thead>
                <tr>
                    <th>#</th>
                    <th>Item</th>
                    <th>Location</th>
                    <th>Variant</th>
                    <th>Quantity</th>
                    <th>Stocked On</th> 
                    <th>Last Updated</th>
                    <th>Manager</th>
                    <th>Edit</th>
                </tr>
            </thead>
        
            <tbody>
                {% for stock in stocks %}
                <tr>
                    <td>{{forloop.counter}}</td>
                    <td>{{stock.variant.product}}</td>
                    <td>{{stock.location}}</td>
                    <td>{{stock.variant}}</td>
                    <td>{{stock.quantity}}</td>
                    <td>{{ stock.created_at }}</td>
                    <td>{{stock.updated_at}}
                        {% if stock.movement_type == 1 %}
                        <span><i class="fa-solid fa-arrow-down text-success"></i></span>
                        {% elif stock.movement_type == 2 %}
                        <span><i class="fa-solid fa-arrow-up text-danger"></i></span>
                        {% elif stock.movement_type == 3 %}
                        <span><i class="fa-solid fa-arrow-down text-success"></i></span>
                        {% else %}
                        <span><i class="fa-solid fa-arrows-up-down text-info"></i></i></span>
                        {% endif %}
                    </td>
                    <td>{{ stock.user.full_name }} ({{ stock.user.get_employee}})</td>
                    {% if stock.variant.is_serialized %}
                    <td><a href="{% url 'stock:edit_stock_with_serials' stock.id %}"><i class="fa-solid fa-pen"></i></a></td>
                    {% else %}
                    <td><a href="{% url 'stock:update_stock' stock.id %}"><i class="fa-solid fa-pen"></i></a></td>
                    {% endif %}
        
                </tr>
                {% endfor %}
            </tbody>
        
            <tfoot>
                <tr>
                    <td colspan='9'>
                        {% show_pagination stocks %}
                    </td>
                </tr>
                <div class="d-flex  align-items-center gap-2">
                    <p class=''>Total Records:{{stocks.count}}</p>
    
                    <p class=''>
                        <a href="{% url 'stock:create_stock' %}"><i class="fa-solid fa-arrows-rotate" style="color: #1f3251;"></i></a>
                    </p>
    
                </div>
            </tfoot>
        
        </table>
    
    {% endif %}
</div>

    
{% endblock table %}

templates/stock/edit_serial_form.html
<form id="edit_serial_form" 
      hx-put="{% url 'stock:serial_detail' serialnumber_obj.pk %}" 
      hx-swap="outerHTML" 
      hx-target="this">
      {% csrf_token %}
    {{ form.as_p }}
    <div class="d-flex gap-2 justify-content-start">
        <button type="button" class="btn btn-sm btn-danger" hx-get="{% url 'stock:serial_detail' serialnumber_obj.pk %}">Cancel</button>
        <button type="submit" class="btn btn-sm btn-primary" form="edit_serial_form">Save</button>
    </div>
</form>

templates/stock/edit_stock_form.html
<form id="edit_stock_form" 
      hx-put="{% url 'stock:stock_detail' stock.pk %}" 
      hx-swap="outerHTML" 
      hx-target="this">
      {% csrf_token %}
    {{ form.as_p }}
    <div class="d-flex gap-2 justify-content-start">
        <button type="button" class="btn btn-sm btn-danger" hx-get="{% url 'stock:stock_detail' stock.pk %}">Cancel</button>
        <button type="submit" class="btn btn-sm btn-primary" form="edit_stock_form">Save</button>
    </div>
</form>

templates/stock/edit_stock_with_serials.html
{% extends "dashboard/home.html" %}
{% load widget_tweaks %}

{% block table %}
    {% if messages %}
        {% for message in messages %}
            <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
                {{ message }}
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            </div>
        {% endfor %}
    {% endif %}

    <div class="container box-container">
        
        <div class="row gap-2">
            <div class="col">

                <div class="p-2 border border-danger">

                    <form action="" method='POST' class="edit_stock_form">
                            {% csrf_token %}
                        <h3 class="px-2 text-danger">Edit Stock</h3>
                            <div class="p-3">
                                <div class="form-group mt-1">
                                    <label for="" class="form-label">Variant</label>
                                    {{ stock_form.variant|add_class:"form-select" }}
                                </div>
                        
                                <div class="form-group mt-1">
                                    <label for="" class="form-label">Location</label>
                                    {{ stock_form.location|add_class:"form-select" }}
                                </div>
                        
                                <div class="form-group mt-1">
                                    <label for="" class="form-label">Quantity</label>
                                    {{ stock_form.quantity|add_class:"form-control" }}
                                </div>
                            </div>
                        <button class="btn m-3 btn-primary">Submit</button>  
                    </form>
                </div>
             
            </div>

            <div class="col border border-danger right-list-box">
    
                <table class="table table-responsive table-sm w-auto ">
                    <thead>
                        <tr>
                            <th>S.N.</th>
                            <th>Item</th>
                            <th>Variant</th>
                            <th>Serial Number</th>
                            <th>Status</th>
                            <th>Edit</th>
                        </tr>
                    </thead>
                        
                    <tbody>
                        
                        {% for sr in serial_numbers %}
                        
                            <tr id="serial_row_{{ sr.id }}">
                                <td>{{ forloop.counter }}</td>
                                <td>{{ sr.item }}</td>
                                <td>{{ sr.product_variant }}</td>
                                <td>{{ sr.serial_number }}</td>
                                <td>{{sr.status|capfirst}}</td>
                                <td><a href="{% url 'stock:update_serial_number' sr.id %}"><i class="fa-solid fa-pen" style="color:blue; cursor:pointer;"></i></a>
                            </tr>       
                                
                        {% endfor %}
    
                    </tbody>
                    <tfoot>
                        Total Records: {{serial_numbers.count}}
                    </tfoot>
                </table>
            </div>
            
        </div>
    </div>


{% endblock table %}

templates/stock/purchase_success.html
{% extends 'dashboard/home.html' %}
{% load static %}

{% block table %}
    <div class="container">
        <div class="row align-items-center">
            <div class="col text-center mx-auto mt-5">
            {% if messages %}
            {% for message in messages %}
                <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
                    {{ message }}
                    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                </div>
            {% endfor %}
            {% endif %}
                <div class="d-flex flex-md-row">
                    <a class='btn btn-warning me-2' href="{% url 'stock:kit_list' %}">Back</a>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/stock/return_success.html
{% extends 'dashboard/home.html' %}
{% load static %}

{% block table %}
    <div class="container">
        <div class="row align-items-center">
            <div class="col text-center mx-auto mt-5">
            {% if messages %}
            {% for message in messages %}
                <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
                    {{ message }}
                    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                </div>
            {% endfor %}
            {% endif %}
                <div class="d-flex flex-md-row">
                    <a class='btn btn-warning me-2' href="{% url 'stock:kit_list' %}">Back</a>
                </div>
            </div>
        </div>
    </div>
{% endblock %}