allocate/urls.py
from django.urls import path
from . import views

app_name = 'allocate'

urlpatterns = [
    path('', views.main_page, name='main'),
    path('list/', views.AllocationView.as_view(), name='allocation_list'),
    path('return/', views.ReturnView.as_view(), name='return_list'),
    path('load-variant/', views.load_variant, name='load_variant'),
    path('update-allocation/<int:pk>/', views.UpdateAllocationView.as_view(), name='update_allocation'), 
    path('return-item/', views.return_item, name='return_item'), 
    path('delete-allocation/', views.delete_allocation, name='delete_allocation'),
    path('products/', views.product_view, name='product_view'),  
    path('products/<int:pk>/', views.product_detail_view, name='product_detail'),
    path('add-item/', views.add_to_allocation_item, name='add_item'),  
    path('cart-items/', views.allocation_cart, name='allocation_cart'),
    path('allocate-items/', views.allocate_items, name="allocate_items"),
    path('allocation-detail/<int:pk>/', views.allocation_detail, name="allocation_detail"),
]

dashboard/urls.py
from django.urls import path
from . import views

app_name = 'dashoboard'

urlpatterns = [
    path('home/', views.dashboard, name='home'),
]

employees/urls.py
from django.urls import path
from .views import register_emp

app_name = 'employees'

urlpatterns = [
   path('register-emp/', register_emp, name='register_emp'),
]

kits/urls.py
from django.urls import path
from . import views

app_name = 'kit'

urlpatterns = [
    path('', views.student_index, name='student_index'),
    path('add-item/', views.CreateItemView.as_view(), name='item_form'),
    path('create-kit/', views.kititem_view, name='create_kititems'),
    path('kititem-form/', views.get_kititem_form, name='kititem_form'),
    path('allocation/list/', views.allocation_list, name="allocate_list"),
    path('allocate-sale/', views.allocate_sale, name="allocate_sale"),
    path('allocate-save/<int:pk>/', views.KitAllocationDetailView.as_view(), name="allocate_save_detail"),
    path('alloccate/update/<int:pk>/', views.UpdateKitAllocation.as_view(), name="update_allocation"),
    path('update/kit/<int:kit_id>/', views.update_kit, name="update_kit"),
    path('delete/kititem/<int:pk>/', views.delete_kititem, name="delete_kititem"),
    path('delete/kit/<int:pk>/', views.delete_kit, name="delete_kit"),
]

orders/urls.py
from django.urls import path
from . import views

app_name = 'orders'

urlpatterns = [
    path('', views.main, name="main"),
    path('order-list/', views.OrdersCreateView.as_view(), name="order_list"),
    path('purchase/list/', views.CreatePurchase.as_view(), name='purchase_list'),
    path('load-variant/', views.load_variant_by_item, name='load_variant'),

    path('invoice-list/', views.CreateInvoice.as_view(), name="invoice_list"),
    path('page-3/', views.page_three, name="page_three"),
    
]

stock/urls.py
from django.urls import path
from . import views
from .forms import (ItemForm, CategoryForm, VariantForm
)
app_name = 'stock'

urlpatterns = [


    path('', views.StockCreate.as_view(), name='create_stock'),
    path('item-detail/<int:pk>/', views.ItemDetailView.as_view(), name='item_detail'),
    path('category-product/', views.load_product_by_category, name='category_product'),
    path('item-variant/', views.load_variant_by_item, name='item_variant'),
    path('item/update/<int:pk>/', views.ItemUpdateView.as_view(), name = 'update_item'),
    path('transaction-list/', views.StockTransactionList.as_view(), name='transaction_list'),
    path('stock/add-success', views.add_success_view, name='add_success'),
    


    path('purchase/<int:pk>/', views.PurchaseDetailView.as_view(), name='purchase_detail'),

    path('issue/list/', views.IssueListView.as_view(), name='kit_list'),
    path('issue/list/<int:pk>/', views.IssueDetailView.as_view(), name='kit_detail'),

    
    path('find/student/', views.filter_student, name='filter_student'),
    
    path('student/list/', views.StudentListView.as_view(), name='student_list'),
    
    path('download/sample/', views.sample_excel, name='sample_excel'),
    
    
    path('issue-new-kit/', views.issue_new_kit, name='issue_new_kit'),
    
    path('exchange-kit/', views.exchage_kit, name='exchange_kit'),

    

]



vendor_urlpatterns = [
    path('vendor/list/', views.VendorsCreateView.as_view(), name='vendor_list'),
]

edit_urlpatterns = [
    path('<int:pk>/edit/', views.edit_stock, name='edit_stock'),
    path('stock-detail/<int:pk>/', views.stock_detail, name='stock_detail'),
    path('serial-detail/<int:pk>/', views.serial_detail, name='serial_detail'),
    path('edit-serial/<int:pk>/', views.edit_serial, name='edit_serial'),
    path('<int:pk>/', views.edit_stock_with_serials, name='edit_stock_with_serials'),
    path('update-serial-number/<int:pk>/', views.UpdateSerialNumber.as_view(), name='update_serial_number'),
    path('update-stock/<int:pk>/', views.UpdateStock.as_view(), name='update_stock'),
]

htmx_urlpatterns = [
    path('check-serializable/', views.check_serializable_view, name='check_serializable'),
    path('add-serial/', views.add_serial_view, name='add_serial'),
    path('remove-input/', views.remove_input_view, name='remove_input'),
]


urlpatterns += htmx_urlpatterns
urlpatterns += edit_urlpatterns
urlpatterns += vendor_urlpatterns

stock_management/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', TemplateView.as_view(template_name='index.html'), name='index'),
    path('catalogue/', include('catalogue.urls', namespace='catalogue')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('stock/', include('stock.urls', namespace='stock')),
    path('kit/', include('kits.urls', namespace='kit')),
    path('auth/', include('authapp.urls', namespace='authapp')),
    path('allocate/', include('allocate.urls', namespace='allocate')),
    path('employees/', include('employees.urls', namespace='employees')),



] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

dashboard/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from authapp.decorators import is_manager

# Create your views here.
@login_required
@is_manager
def dashboard(request):
    return render(request, 'dashboard/home.html')

templates/dashboard/home.html
{% extends 'base.html' %}   
{% load static %}
{% load nav_extras %}
{% block content %}
 
{#{% url 'authapp:add_student' as ADDSTUDENT %}#}
{% url 'stock:add_item' as ADDITEM %}
{% url 'stock:student_list' as STUDENTLIST %}
{% url 'stock:create_stock' as STOCKLIST %}
{% url 'stock:purchase_list' as PURCHASELIST %}
{% url 'allocate:main' as ALLOCATIONS %}
{% url 'stock:kit_list' as KITLIST %}
{% url 'stock:vendor_list' as VENDORS %}
{% url 'orders:main' as MAIN %}


<div class="container-fluid my-3" id="main_container">

    <div class="row h-100 overflow-y-auto" >

        {% comment %} <--! home page side navigation. --> {% endcomment %}

        <div class="col-md-3 col-lg-2 col-sm-12 col-12  sidebar ">

            {% block sidenav %}

            <ul class="side-navigation ">
                {% comment %} <li><a href="" class="{% if request.path == ADDSTUDENT %} active {% endif %}"><i class="fa-solid fa-graduation-cap me-2" style="color: #ffffff;"></i>Add Student</a></li> {% endcomment %}

                <li><a href="{% url 'catalogue:main' %}" class="{% active_class '/catalogue/' %}"><i class="fa-solid fa-square-plus me-2" style="color: #5d0607ff;"></i>Catalogue</a></li>


                <li><a href="{% url 'orders:main' %}" class="{% active_class '/orders/' %}"><i class="fa-solid fa-bag-shopping me-2" style="color: #7e080a;"></i>Orders</a></li>

                <li><a href="{% url 'stock:create_stock' %}" class="{% active_class_end '/stock/' %}"><i class="fa-solid fa-box-open me-2" style="color: #7e080a;"></i>Stock</a></li>

                <li><a href="{% url 'allocate:main' %}" class="{% active_class '/allocate/' %}"><i class="fa-solid fa-money-bill-transfer me-2" style="color: #7e080a;"></i>Allocations</a></li>
                
                <li><a href="{% url 'stock:vendor_list' %}" class="{% active_class_end 'vendor/list/' %}"><i class="fa-solid fa-address-book me-2" style="color: #7e080a;"></i>Vendors</a></li>

                <li><a href="{% url 'employees:register_emp' %}" class="{% active_class '/employees/' %}"><i class="fa-solid fa-ribbon me-2" style="color: #7e080a;"></i>Employees</a></li>


                
                {% comment %} <li><a href="{% url 'stock:student_list' %}" class="{% if request.path == STUDENTLIST %} active {% endif %}"><i class="fa-solid fa-database me-2" style="color: #ffffff;"></i>Students Data</a></li> {% endcomment %}






                {% comment %} <li><a href="{% url 'stock:kit_list' %}" class="{% if request.path == KITLIST %} active {% endif %}"><i class="fa-solid fa-gift me-2" style="color: #ffffff;"></i>Kits Data</a></li> {% endcomment %}


              
                {% comment %} <li><a href="{% url 'stock:search_kit' %}" class="{% if request.path == '/stock/return/kit/' %} active {% endif %}"><i class="fa-solid fa-rectangle-xmark me-2" style="color: #ffffff;"></i>Return Kits</a></li> {% endcomment %}

                {% comment %} <li><button type='button' data-bs-target='#studentsearch' data-bs-toggle='modal'   class="{% if request.path == '/stock/return/kit/' %} active {% endif %} ms-3 border-0 w-100 text-start bg-transparent text-light" ><i class="fa-solid fa-rectangle-xmark me-2" style="color: #ffffff;" ></i>Exchange Item</button></li> {% endcomment %}
            </ul>
            {% endblock sidenav %}

            <div class="modal fade" tabindex="-1" id="studentsearch"  data-bs-backdrop="static">
                <div class="modal-dialog">
                    <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title">Search Student</h5>
                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                    </div>
                    <div class="modal-body">
                        <form method="post" class='p-2' id='searchform'>
                                {% csrf_token %}
                                
                                <div class="form-group">
                                    {% comment %} <label for="">Enrollement Number</label> {% endcomment %}
                                    <input type="text" name="enrollement" placeholder="Enter enrollement Number" class="form-control" required>
                                </div>
                                <div class="form-group">
                                    <label for="" class="text-center mt-2 w-100">OR</label>
                                    {% comment %} <label for="" >Name</label> {% endcomment %}
                                    <input type="text" name='name' class="form-control" placeholder="Enter full name">
                                </div>


                                <div class="form-group">
                                    <button type="button" class="btn btn-warning mt-3"
                                    hx-post="#"
                                        hx-trigger="click"
                                        hx-swap="outerHTML"
                                        hx-target="this">
                                    Search</button>
                                </div>
                                        
                                    
                            <div id="result" class="mt-2"></div>

                        </form>
                    </div>
                    </div>
                </div>
            </div>   

        </div>

        <div class="col-lg-10 col-md-9 col-sm-12 col-12 p-3 overflow-y-auto"  style="max-height:100vh;" >
            {% block table %}
            {% endblock %}
        </div>
    </div>

    <div class="row align-items-center">
        <div class="col text-bg-dark">
            <div class='d-flex justify-content-center align-items-center'>
                <p class="mt-2">&copy; SCHOLARS DEN. All Rights Reserved</p>
            </div>
        </div>
    </div>
</div>


    <div class="modal returnmodal fade" tabindex="-1" id="returnkit" data-bs-backdrop="static" data-bs-keyboard="false">
        <div class="modal-dialog ">
            <div class="modal-content">

                <div class="modal-header">
                    <h5 class="modal-title">Return Kit</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>

                <div class="modal-body">
                    <h5 class="modal-title">Are you sure you want to return kit</h5>
                </div>
                    <div class="modal-footer">
                    <button type="button" class="btn btn-danger" data-bs-dismiss="modal">Close</button>
                    <button type="submit" class="btn btn-primary" form="returnform">Confirm</button>
                </div>

            </div>
        </div>
    </div>


<script>

    const returnBtn = document.getElementById('returnbtn')
    const searchModal = document.getElementById('studentsearch')

    searchModal.addEventListener('shown.bs.modal', _ => {
        const searchResultWraper = document.querySelector('.detail-wraper')
    })



  function switchModal() {
      //const currentModal = bootstrap.Modal.getInstance(document.getElementById(currentModalId));
      const returnBtn = document.getElementById('returnbtn')



      const currentModel = document.getElementById('studentsearch')

      console.log(currentModel)
      //currentModal.hide();

      // Wait for the first modal to fully close, then open the next one
      setTimeout(() => {
         // const newModal = new bootstrap.Modal(document.getElementById(targetModalId));
         // newModal.show();
      }, 500); // Adjust if your animation speed differs
  }
</script>


{% endblock %}